%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/camera/imu"
image0_topic: "/camera/fisheye1/image_raw"
image1_topic: "/camera/fisheye2/image_raw"
output_path: "/home/jaron/output/"

cam0_calib: "t265_cam1.yaml"
cam1_calib: "t265_cam2.yaml"
image_width: 848
image_height: 800   


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -9.9994778419428387e-01, -7.0110915732418235e-03,
       7.4346136345369730e-03, 1.6359351811300740e-02,
       7.0786969534837067e-03, -9.9993348108469449e-01,
       9.1063414874834950e-03, 6.4166551964656244e-03,
       7.3702736980363268e-03, 9.1584933694107175e-03,
       9.9993089814487601e-01, 3.3311180120125820e-03, 0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -9.9997294035530415e-01, -7.3179311387122784e-03,
       -7.5262275839588590e-04, -4.6605198147464354e-02,
       7.3076304120939040e-03, -9.9989031187063904e-01,
       1.2882653647308524e-02, 7.2365875293144448e-03,
       -8.4681457688828734e-04, 1.2876805158320001e-02,
       9.9991673193020780e-01, 4.7114032150622452e-03, 0., 0., 0., 1. ]

#Multiple thread support
multiple_thread: 1

#Gpu
use_gpu: 1
use_gpu_acc_flow: 1


#feature traker paprameters
max_cnt: 500           # max feature number in feature tracking
min_dist: 30           # min distance between two features 
freq: 0             # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 5.0        # ransac threshold (pixel)
show_track: 1          # publish tracking image as topic
flow_back: 1        # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.01  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 2.3357467241439975e-02          # accelerometer measurement noise standard deviation. 
gyr_n: 2.0676984015015457e-03         # gyroscope measurement noise standard deviation.     
acc_w: 1.1241693752452474e-03        # accelerometer bias random work noise standard deviation.  
gyr_w: 1.7699599856527790e-05       # gyroscope bias random work noise standard deviation.     
g_norm: 9.8100     # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

load_previous_pose_graph: 1 # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/jaron/output/pose_graph/" # save and load path
save_image: 1 # save image in pose graph for visualization prupose; you can close this function by setting 0
