%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/camera/imu"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"
output_path: "/home/jaron/output/"

cam0_calib: "d455_cam1.yaml"
cam1_calib: "d455_cam2.yaml"
image_width: 848
image_height: 480   


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 9.9995469827089289e-01, 5.0975019909797609e-03,
       8.0384625034533707e-03, -2.8068363233905477e-02,
       -5.1083821160640731e-03, 9.9998606293135062e-01,
       1.3335573528020462e-03, -1.9735050161484040e-04,
       -8.0315526595886293e-03, -1.3745604784413936e-03,
       9.9996680182162412e-01, 1.5391360406325317e-02, 0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 9.9995299758843503e-01, 5.1993842978924117e-03,
       8.1834599544422983e-03, 6.2668069570767856e-02,
       -5.2104778597173579e-03, 9.9998553441440885e-01,
       1.3348716801365201e-03, -7.0936978871864297e-04,
       -8.1764010650484924e-03, -1.3774486748569293e-03,
       9.9996562395952970e-01, 1.4792975611420579e-02, 0., 0., 0., 1. ]

#Multiple thread support
multiple_thread: 1

#Gpu
use_gpu: 0
use_gpu_acc_flow: 0


#feature traker paprameters
max_cnt: 300           # max feature number in feature tracking
min_dist: 15           # min distance between two features 
freq: 0             # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1          # publish tracking image as topic
flow_back: 1        # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 1.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 1.7261499019137486e-02         # accelerometer measurement noise standard deviation. 
gyr_n: 2.5525566282650963e-03       # gyroscope measurement noise standard deviation.     
acc_w: 3.0825482769472466e-04            # accelerometer bias random work noise standard deviation.  
gyr_w: 3.1197068186773590e-05     # gyroscope bias random work noise standard deviation.     
g_norm: 9.81     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

load_previous_pose_graph: 1 # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/jaron/output/pose_graph/" # save and load path
save_image: 1 # save image in pose graph for visualization prupose; you can close this function by setting 0
